Summary:	Utility to unpack Firefox lz4json files
Summary(pl.UTF-8):	Narzędzie do rozpakowywania plików lz4json z Firefoksa
Name:		lz4json
Version:	2
Release:	1
License:	BSD-like
Group:		Applications/File
#Source0Download: https://github.com/andikleen/lz4json/releases
Source0:	https://github.com/andikleen/lz4json/archive/v%{version}/%{name}-%{version}.tar.gz
# Source0-md5:	639e40a0427c74f8d521a3a7729348fb
URL:		https://github.com/andikleen/lz4json
BuildRequires:	lz4-devel
BuildRequires:	pkgconfig
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
A little utility to unpack lz4json files as generated by Firefox's
bookmark backups and session restore. This is a different format from
what the normal lz4 utility expects.

%description -l pl.UTF-8
Niewielkie narzędzie do rozpakowywania plików lz4json, generowanych
przez kopie zapasowe zakładek i sesji Firefoksa. Jest to format inny
niż oczekiwany przez zwykłe narzędzie lz4.

%prep
%setup -q

%build
%{__make} \
	CC="%{__cc}" \
	CFLAGS="%{rpmcflags} %{rpmcppflags} -Wall" \
	LDFLAGS="%{rpmldflags}"

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_bindir},%{_mandir}/man1}

install lz4jsoncat $RPM_BUILD_ROOT%{_bindir}
cp -p lz4jsoncat.1 $RPM_BUILD_ROOT%{_mandir}/man1

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README
%attr(755,root,root) %{_bindir}/lz4jsoncat
%{_mandir}/man1/lz4jsoncat.1*
